# Generated by Django 5.2.17 on 2026-09-22 08:46

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, default=apps.orders.models.generate_order_number, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_type', models.CharField(choices=[('retail', 'Retail Household'), ('wholesale', 'Wholesale Commercial')], default='retail', max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_zone', models.CharField(blank=True, default='Kochi Central', max_length=100)),
                ('delivery_slot', models.CharField(default='Morning (06:00 AM - 09:00 AM)', max_length=100)),
                ('preferred_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery (COD)'), ('upi_direct', 'UPI Direct (GPay / PhonePe / Paytm)'), ('bank_transfer', 'Commercial Bank Transfer (B2B)'), ('store_pickup', 'Direct Mandi / Store Pickup')], default='cash_on_delivery', max_length=30)),
                ('is_paid', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending Confirmation'), ('Confirmed', 'Order Confirmed'), ('Preparing', 'Harvesting & Packing'), ('Ready', 'Ready for Dispatch'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_wholesale_price_applied', models.BooleanField(default=False)),
            ],
        ),
    ]
