# Generated by Django 5.2.17 on 2026-09-22 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('stock_quantity', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('malayalam_name', models.CharField(blank=True, max_length=150, null=True)),
                ('arabic_name', models.CharField(blank=True, max_length=150, null=True)),
                ('origin', models.CharField(blank=True, default='Kerala Farms', max_length=120)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('min_wholesale_qty', models.PositiveIntegerField(default=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_organic', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MandiDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandi_hub', models.CharField(default='Kerala Central Mandi', max_length=100)),
                ('auction_date', models.DateField()),
                ('morning_retail_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('morning_wholesale_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_trend', models.CharField(blank=True, default='Normal Supply', max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandi_rates', to='products.product')),
            ],
            options={
                'ordering': ['-auction_date', 'product__name'],
                'unique_together': {('product', 'auction_date', 'mandi_hub')},
            },
        ),
    ]
